"use client";

import { useMemo } from "react";
import Link from "next/link";
import { Container, PageHeader } from "@/components/ui/Container";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Stat } from "@/components/ui/Stat";
import { Spinner } from "@/components/ui/Spinner";
import { NetworkTabs } from "@/components/network/NetworkTabs";
import { useMantleFees, type MantleFeeProtocol } from "@/hooks/useMantleFees";
import { formatUsd } from "@/lib/format";
import { cn } from "@/lib/cn";

export default function MantleFeesPage() {
  const { data, isLoading, isError, error } = useMantleFees();

  const protocols = useMemo<readonly MantleFeeProtocol[]>(
    () => data?.protocols ?? [],
    [data],
  );

  // Share-of-total uses the largest listed 24h fee figure as the bar baseline so
  // the top protocol fills the bar and the rest scale relative to it.
  const maxFees24h = useMemo(
    () => protocols.reduce((max, p) => Math.max(max, p.fees24h ?? 0), 0),
    [protocols],
  );

  return (
    <Container className="py-12">
      <PageHeader
        eyebrow="Mantle"
        title="Fees & Revenue"
        description="Fees generated by protocols on Mantle over the last 24h and 7d, aggregated from DefiLlama and ranked by 24h fees. Figures reflect real on-chain protocol revenue and move with the market."
        actions={
          <Link
            href="/network"
            className="text-sm font-medium text-gold transition-colors hover:text-gold/80"
          >
            ← Network
          </Link>
        }
      />

      <NetworkTabs />

      {!isLoading && !isError && data && (
        <div className="mb-6 grid gap-4 sm:grid-cols-3">
          <Stat
            label="24h Fees"
            value={data.total24h !== null ? formatUsd(data.total24h) : "—"}
            hint="Across all Mantle protocols"
          />
          <Stat
            label="7d Fees"
            value={data.total7d !== null ? formatUsd(data.total7d) : "—"}
          />
          <Stat
            label="Protocols"
            value={protocols.length.toString()}
            hint="Ranked by 24h fees"
          />
        </div>
      )}

      {isLoading ? (
        <div className="flex justify-center py-20">
          <Spinner className="h-8 w-8" />
        </div>
      ) : isError ? (
        <Card className="border-crimson/30 bg-crimson/5 p-10 text-center">
          <p className="font-display text-lg font-semibold text-crimson-soft">
            Could not load Mantle fees & revenue.
          </p>
          {error instanceof Error && (
            <span className="mt-1 block text-sm text-muted">{error.message}</span>
          )}
        </Card>
      ) : protocols.length === 0 ? (
        <div className="rounded-2xl border border-border bg-surface/60 p-10 text-center text-muted">
          No protocol fees reported for Mantle right now.
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          {protocols.map((protocol, index) => {
            const rank = index + 1;
            const isTop = rank === 1;
            const fees24h = protocol.fees24h ?? 0;
            const sharePct = maxFees24h > 0 ? (fees24h / maxFees24h) * 100 : 0;
            return (
              <Card
                key={protocol.name}
                glow={isTop}
                className={cn(isTop && "border-gold/40")}
              >
                <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
                  <div className="flex min-w-0 items-start gap-4">
                    <div
                      className={cn(
                        "flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border font-display text-lg font-bold",
                        isTop
                          ? "border-gold/40 bg-gold/15 text-gold"
                          : "border-border bg-surface/60 text-muted",
                      )}
                    >
                      {rank}
                    </div>
                    <div className="min-w-0">
                      <span className="font-display text-lg font-semibold text-foreground">
                        {protocol.name}
                      </span>
                      {protocol.category !== null && (
                        <div className="mt-2">
                          <Badge tone="info">{protocol.category}</Badge>
                        </div>
                      )}
                    </div>
                  </div>
                  <div className="shrink-0 sm:text-right">
                    <p className="text-xs uppercase tracking-wider text-muted">24h Fees</p>
                    <p className="font-display text-3xl font-bold text-gold">
                      {protocol.fees24h !== null ? formatUsd(protocol.fees24h) : "—"}
                    </p>
                  </div>
                </div>

                <div className="mt-5">
                  <div className="h-2 w-full overflow-hidden rounded-full border border-border bg-surface/60">
                    <div
                      className={cn(
                        "h-full rounded-full",
                        isTop ? "bg-gold" : "bg-gold/50",
                      )}
                      style={{ width: `${sharePct}%` }}
                    />
                  </div>
                </div>

                <div className="mt-5 grid gap-4 sm:grid-cols-2">
                  <Stat
                    label="24h Fees"
                    value={protocol.fees24h !== null ? formatUsd(protocol.fees24h) : "—"}
                  />
                  <Stat
                    label="7d Fees"
                    value={protocol.fees7d !== null ? formatUsd(protocol.fees7d) : "—"}
                  />
                </div>
              </Card>
            );
          })}
        </div>
      )}

      <p className="mt-8 text-center text-xs text-muted">
        Source:{" "}
        <Link
          href="https://defillama.com/fees/chain/Mantle"
          target="_blank"
          rel="noreferrer"
          className="text-gold hover:text-gold/80"
        >
          DefiLlama
        </Link>
      </p>
    </Container>
  );
}
